### ISSUE TITLE
docs of DiffUNet

### ISSUE THREAD

**Issue by tachella** [deepinv/deepinv#101]
The current name "The full UNet model with attention and timestep/noise_level embedding" is not great. We should change it for something that refers to Ho et al

**Comment by matthieutrs** [comment]
Thanks Julian, I've updated [here](https://github.com/deepinv/deepinv/blob/weights_reference/deepinv/models/diffunet.py#L15)!

**Comment by tachella** [comment]
perfect, I close the issue
