### ISSUE TITLE
TGV denoiser

### ISSUE THREAD

**Issue by samuro95** [deepinv/deepinv#106]
The following code 

```
denoiser = dinv.models.TGV(n_it_max=1000) 
sigma = .1
xnoisy = x+torch.randn_like(x)*sigma
xhat = denoiser(xnoisy, sigma)
dinv.utils.plot([x, xnoisy, xhat], `titles=['original','noisy','restored'])
```

seem to not denoise properly.

**Comment by matthieutrs** [comment]
Yes, this is because the `sigma` parameter in the TGV denoiser (and in variational denoisers) are equal to the regularisation parameter when solving min 1/2|Ax-y|^2+lambda*g(x). Something like `10*sigma` tends to work well for TGV but it depends on the image.

**Comment by samuro95** [comment]
I see, thanks !
