### ISSUE TITLE
Allow `str` to be passed as directory name in demo dataset loader

### ISSUE THREAD

**Issue by Andrewwango** [deepinv/deepinv#109]
https://github.com/deepinv/deepinv/blob/2e2f27167ef95f44154b379bb4f844170b384123/deepinv/utils/demo.py#L54-L57

Change to `from pathlib import Path; dataset_dir = Path(data_dir) / dataset_name `

**Comment by samuro95** [comment]
Thanks ! It will be changed with this PR #103
