### ISSUE TITLE
A bug in the implementation of L1 and Tikhonov priors

### ISSUE THREAD

**Issue by MohammadSadeghSalehi** [deepinv/deepinv#118]
When using **dinv.optim.prior.L1()**, it raises the following error:
**AttributeError: 'L1' object has no attribute '_backward_hooks'**

Suggested Fix:

To address this issue, it is recommended to modify the __init__ method in the L1 class (as well as the Tikhonov class) by adding the following line:
**super().__init__(*args, **kwargs)**
This ensures that the initialization of the parent class is correctly called.

Additionally, consider updating the input arguments of the g and prox methods in the prior parent class. Modify them to include *args and **kwargs for consistency with the derived classes:

For the g method:
**def g(self, x, *args, **kwargs)**

For the prox method:
**def prox(self, x, *args, gamma=1.0, stepsize_inter=1.0, max_iter_inter=50, tol_inter=1e-3, **kwargs)**
These adjustments should resolve the reported AttributeError.

**Comment by samuro95** [comment]
Thanks a lot for noticing. It will be resolved with #121.
