### ISSUE TITLE
fastmri requirement

### ISSUE THREAD

**Issue by gschramm** [deepinv/deepinv#134]
Hi deepinvs,

if I understand correctly, you "only" need `fastmri` in this demo [here](https://github.com/deepinv/deepinv/blob/72a182a442561fe05523d488c06e3f6ed01c8cda/deepinv/utils/demo.py#L15).
I suppose that the core (and all unit tests) of `deepinv` also works without `fastmri`.

If that is the case, I think it would be better to remove `fastmri` as an explicit dependency
to potentially avoid the "dependency hell"

Georg

PS: I am asking since I am trying to get `deepinv` on `conda-forge` which needs `fastmri` on conda-forge first,
which is harder than I tought ;)

**Comment by matthieutrs** [comment]
Hi Georg, thanks a lot for the feedback! You are completely correct, we could actually remove the fastmri dependency. I'll close this issue when we remove it.

**Comment by gschramm** [comment]
Great. That will facilitate the conda-forge build a lot :) 

Would it be also possible to be a bit more specific (restrictive) in the required versions of the dependencies in [pyproject.toml](https://github.com/deepinv/deepinv/blob/main/pyproject.toml)?
I can e.g. imaging that you need a torch version that is not "too old".

**Comment by matthieutrs** [comment]
Sure! From memory we tested in `torch>1.9` but for other dependencies I don't remember, I'll have a check.

**Comment by matthieutrs** [comment]
Hi Georg, we've finally removed the fastmri dependency - which beared several spurious dependencies like pytorch-llightning... Closing this issue for now, don't hesitate to re-open if it didn't fix for you!
