### ISSUE TITLE
BM3D denoiser 

### ISSUE THREAD

**Issue by svvenkatakrishnan** [deepinv/deepinv#139]
I am trying to use the Bm3D denoiser as a prior model for a gray-scale imaging problem.

However, I get the following error: 

denoiser= BM3D()
tst=denoiser.forward(y,sigma=0.5)

where y is a 1 X 1 X 128 X 128 torch tensor (torch.Size([1, 1, 128, 128])). 

However, I get this error: 

    41 out = torch.zeros_like(x)
     43 for i in range(x.shape[0]):
     44     out[i, :, :, :] = array2tensor(
---> 45         bm3d.bm3d(tensor2array(x[i, :, :, :]), sigma)
     46     )
     47 return out

IndexError: too many indices for tensor of dimension 3

I use the same tensor with other denoisers in deep inverse and it seems to work fine. 

Any suggestions or is there an issue ?

**Comment by matthieutrs** [comment]
Thanks for spotting this! The format for grayscale images in bm3d required to skip the channel dimension, which caused the bug.

**Comment by svvenkatakrishnan** [comment]
Thank you for the fix!
