### ISSUE TITLE
`eval_psnr` is not saved in `training_utils.train` 

### ISSUE THREAD

**Issue by vsechaud** [deepinv/deepinv#144]
`eval_psnr` is reset in line 185-186 https://github.com/deepinv/deepinv/blob/98df7a7cb6e7a968a44a9c01f9745cd1a3dbd232/deepinv/training_utils.py#L185-L186 before to being saved in `save_model`, which results in saving 0 as `eval_psnr`.

**Comment by Andrewwango** [comment]
Does setting `eval_psnr=test_psnr` in `save_model(` fix it?

**Comment by Andrewwango** [comment]
> Does setting `eval_psnr=test_psnr` in `save_model(` fix it?

@tachella this should be already resolved in #181

**Comment by tachella** [comment]
indeed
