### ISSUE TITLE
small bug in optim.L2.forward()

### ISSUE THREAD

**Issue by tobias-liaudat** [deepinv/deepinv#157]
Hi guys,

It seems there's a small bug in the `L2.forward()`, as the `sigma` (or `L2.norm` as it is stored in the `L2` class) of the Gaussian likelihood is not taken into account in the forward function or the `L2.d()`. 

It could be fixed by, for example, replacing [this line](https://github.com/deepinv/deepinv/blob/08944ac02c89fcc3ca229a2565bdcdf19da517c7/deepinv/optim/data_fidelity.py#L260):
`return d`
by:
`return d * self.norm`

**Comment by matthieutrs** [comment]
Thanks for spotting this Tobias! We've fixed it :)

**Comment by tobias-liaudat** [comment]
Thanks for merging it @matthieutrs :)
