### ISSUE TITLE
Example broken

### ISSUE THREAD

**Issue by fabian-sp** [deepinv/deepinv#186]
Hi,

I ran your [example](https://deepinv.github.io/deepinv/auto_examples/optimization/demo_TV_minimisation.html#sphx-glr-auto-examples-optimization-demo-tv-minimisation-py) in a Colab, and when calling

```
x_model, metrics = model(
    y, physics, x_gt=x, compute_metrics=True
)
```
I got the following error:

```
[/usr/local/lib/python3.10/dist-packages/deepinv/optim/prior.py](https://localhost:8080/#) in g(self, x, ths, **kwargs)
    315         :return: (torch.Tensor) prior :math:`\tau g(x)`.
    316         """
--> 317         return ths * torch.sum(torch.sqrt(torch.sum(self.nabla(x) ** 2, axis=-1)))
    318 
    319     def prox(self, x, ths=1.0, gamma=1.0, *args, **kwargs):

TypeError: unsupported operand type(s) for *: 'NoneType' and 'Tensor'
```

The `deepinv` version was 0.1.1 (installed via pip).

**Comment by Andrewwango** [comment]
Can you reproduce this with `pip install git+https://github.com/deepinv/deepinv.git#egg=deepinv`?

**Comment by tachella** [comment]
perfect, I will close this issue then.
