### ISSUE TITLE
Backpropagation involving TV prior fails

### ISSUE THREAD

**Issue by Nils-Laurent** [deepinv/deepinv#194]
Backpropagation involving TV prior fails with a message containing:
"RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed)."

Here is a reproducing example https://gist.github.com/Nils-Laurent/3f9205daaf59f39a455f52fe4180ff35

It could be worth checking the function _prox_sigma_g_conj_ of the class _TVDenoiser_

**Comment by samuro95** [comment]
#196

**Comment by tachella** [comment]
this issue should be solved with #196
