### ISSUE TITLE
Proposed example in BaseOptim

### ISSUE THREAD

**Issue by ChapponE** [deepinv/deepinv#20]
In the example in BaseOptim:
RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x1 and 3x3) 
for y = physics.A(x)
Solution? replace x = torch.ones(1, 1, 1, 3) by  x = torch.ones(1, 1, 3, 1)

NameError: name 'X' is not defined. Did you mean: 'x'?
for X = iterator(X, params) X is not initialized. Why not replace params by cur_params=params_algo, y=y, physics=physics, prior=prior ?

Best regards.

**Comment by matthieutrs** [comment]
Hi! Thanks for noticing :)

I'm updating this example in [this PR](https://github.com/deepinv/deepinv/pull/19).

**Comment by matthieutrs** [comment]
Closing this as #19 is now merged!
