### ISSUE TITLE
`Trainer` online measurements `generator.step` should include batch size

### ISSUE THREAD

**Issue by Andrewwango** [deepinv/deepinv#207]
Physics generators have a `batch_size` argument in `step`, and this should be passed in get online measurements in Trainer.

https://github.com/deepinv/deepinv/blob/13885b05b073702e38e412a34fccc9f8d11c4b9e/deepinv/training/trainer.py#L354

I propose:

`params = self.physics_generator.step(batch_size=x.shape[0])`

**Comment by tachella** [comment]
This has been solved in #212
