### ISSUE TITLE
MInor confusion/error in docs 

### ISSUE THREAD

**Issue by svvenkatakrishnan** [deepinv/deepinv#209]
In the doc string for  https://deepinv.github.io/deepinv/stubs/deepinv.optim.optim_iterators.GDIteration.html#deepinv.optim.optim_iterators.GDIteration

In the first line the \lambda is multiplied by the "f". However if the forward(x, cur..) doc string \lambda is multiplied by g.

**Comment by matthieutrs** [comment]
Thanks for spotting this, that's indeed a typo!

**Comment by tachella** [comment]
Thanks for spotting this, it has been fixed in PR #211.
