### ISSUE TITLE
Example: Image deblurring with Total-Variation (TV) prior (Not working)

### ISSUE THREAD

**Issue by rajmadan96** [deepinv/deepinv#215]
Hello,

The example titled "Image deblurring with Total-Variation (TV) prior" is encountering an issue. Specifically, upon instantiating the model with "dinv.optim.prior.TVPrior(n_it_max=20)", I'm encountering the error message "TypeError: unsupported operand type(s) for *: 'NoneType' and 'Tensor'". My assessment suggests that defining "ths=1.0" could resolve this issue.

Thank you in advance!

**Comment by matthieutrs** [comment]
Hi @rajmadan96! I've checked but things seem ok.

Out of curiosity, does the following work for you?

```python
foo = torch.randn(1,3,128,128)
denoiser = dinv.optim.prior.TVPrior(n_it_max=100)
out = denoiser.prox(foo, sigma)
```

If not, it may be that your version of deepinv may not be up-to-date. In particular, the examples such as [the one you refer to](https://deepinv.github.io/deepinv/auto_examples/optimization/demo_TV_minimisation.html#sphx-glr-auto-examples-optimization-demo-tv-minimisation-py) are ran by github's CI, so those should run on your side too (if you have the latest version of the code!).

**Comment by rajmadan96** [comment]
Hi @matthieutrs,

Thank you for your prompt response.

I ran the provided code snippet, and it executed successfully. However, I'm still encountering the issue I mentioned earlier. In order to provide more clarity on the problem, I have attached a screenshot of the error message for your reference.

I'm using the latest version of deepinv.

![Screenshot from 2024-05-15 17-20-37](https://github.com/deepinv/deepinv/assets/62553056/2595a096-02fe-48e6-aa21-dd6af0e541e1)

**Comment by matthieutrs** [comment]
Hi @rajmadan96! I am not sure how `model` was instanciated in your code; from the [example](https://deepinv.github.io/deepinv/auto_examples/optimization/demo_TV_minimisation.html#sphx-glr-auto-examples-optimization-demo-tv-minimisation-py), it is necessary to set a params_algo dictionary containing the regularization parameter and stepsize of the algo, e.g. 

```python
# Algorithm parameters
stepsize = 1.0
lamb = 1e-2  # TV regularisation parameter
params_algo = {"stepsize": stepsize, "lambda": lamb}
max_iter = 300
early_stop = True

# Instantiate the algorithm class to solve the problem.
model = optim_builder(
    iteration="PGD",
    prior=prior,
    data_fidelity=data_fidelity,
    early_stop=early_stop,
    max_iter=max_iter,
    verbose=verbose,
    params_algo=params_algo,
)
```

Would setting params_algo fix your issue? If not, feel free to share a reproducible snippet of code ☺️

**Comment by rajmadan96** [comment]
Hi @matthieutrs,

I initially installed the package using pip. However, after cloning the repository and running the code again, it works perfectly! Thank you once again :)
