### ISSUE TITLE
couldn't find class file in data set

### ISSUE THREAD

**Issue by Afsinoz** [deepinv/deepinv#22]
I am getting this error when I want to run the example 'demo_train_inpainting.py' in the example file:

"FileNotFoundError: Couldn't find any class folder in ../deepinv/datasets/DRUNET."

**Comment by matthieutrs** [comment]
Hi! Did you dowload the dataset yourself? Following the torch dataset convention, the code assumes that the dataset is organised as 
```
DRUNet/0/img_0.png
              .../img_1.png
              .../img_2.png
...
```
(the /0/ folder corresponds to classes when working on classification tasks).

**Comment by samuro95** [comment]
Closing this issue as the dataset downloading code has been updated
