### ISSUE TITLE
ULAIterator having issues with GPU-based torch devices 

### ISSUE THREAD

**Issue by tobias-liaudat** [deepinv/deepinv#235]
When the torch device is not "cpu" the iterator has some issues with variables stored in gpu/cpu devices.

PR with a fix incoming.

**Comment by samuro95** [comment]
The problem comes from the stepsize variable of ULA_iterator that needs always to be a float. In future PR we will 1) add documentation to the ULA_iterator class to specify the type of each variable and 2) Use the typing syntax in order to specify that the stepsize needs to be a float.

**Comment by tobias-liaudat** [comment]
Sounds good! Feel free to close this PR
