### ISSUE TITLE
Rand num gens for physics generators

### ISSUE THREAD

**Issue by Andrewwango** [deepinv/deepinv#243]
Each physics generator should have a `rng` attribute that is set at initialisation from a seed `self.rng = torch.Generator().manual_seed(seed)` and also possible to set at forward in `step(seed=None)` if wanted. Then all randomness should have a `generator=self.rng` (for torch) or `self.rng.rand(...)` (for numpy).

Advantages 

- Allow deterministic generation (solving #201 and #202)
- Better for unit tests
- Allow both torch generators and numpy rngs

**Comment by minh-hai-nguyen-712** [comment]
That's a good idea for reproducibility. I'll take care of this!

**Comment by minh-hai-nguyen-712** [comment]
That's a good idea for reproducibility. I'll work on this!
