### ISSUE TITLE
wandb issues in training_utils.py

### ISSUE THREAD

**Issue by ChapponE** [deepinv/deepinv#25]
These errors occur only if  wandb_vis=False in the test funtion, wandb is not imported and initialized in the script:

- If plot_metrics is set to True in the test function  in training_utils, I get an error  cause of the wandb.log at line  355 in training_utils.py : wandb.errors.Error: You must call wandb.init() before wandb.plot_table() 

- If plot_metrics is set to False I get the error : TypeError: 'NoneType' object is not subscriptable at line 293 of training_utils.py

It seems that there is not settings where calling test with wanbd_vis=False doesn't return an error if wanbd is not initialized in the script which call the test function.
It seems that initialize wandb is mandatory even if user don't want to use it. 

I'm not sure if I have been clear, and I'm uncertain whether it's an error or an incorrect usage.

**Comment by samuro95** [comment]
Closing this issue has training_utils.py has been updated.
