### ISSUE TITLE
Inconsistency between documentation and usage

### ISSUE THREAD

**Issue by VinceHerfeld** [deepinv/deepinv#254]
To specify the activation functions for the DRUNet architecture in `deepinv.models.drunet` we can pass through `act_mode` parameter in the `__init__` function different characters. For Softplus it is said to use "S" (capital) but in the `deepinv.models.drunet` source code for the `conv` layer the `if` statement checks for "s" (lowercase). This raises `NotImplementedError: Undefined type: `.

**Comment by samuro95** [comment]
Thanks for reporting the inconsistency. Solved in #260.
