### ISSUE TITLE
Member `train` of `GSPnP` seems to cause an error when performing model.eval()

### ISSUE THREAD

**Issue by Nils-Laurent** [deepinv/deepinv#257]
When performing `model.eval()` using PnP prior with GSDRUNet, I have the following error `TypeError: 'bool' object is not callable` wich follows the call `return self.train(False)` on a nn.Module. I think this is due to the member named `train` in class `GSPnP` which is set in the `__init__` method. Since I don't know what `eval` exactly does, I am unsure on how to fix it

**Comment by samuro95** [comment]
#260
