### ISSUE TITLE
dinv.physics.PoissonNoise incompatible with dinv.physics.BlurFFT

### ISSUE THREAD

**Issue by abhijits08** [deepinv/deepinv#273]
After the latest updates to the library, when dinv.physics.PoissonNoise is used as the noise model in dinv.physics.BlurFFT, we get the following error: " TypeError: PoissonNoise.update_parameters() missing 1 required positional argument: 'gain' ".

It can be solved by modifying self.noise_model.update_parameters(**kwargs) in the update_parameters function of the BlurFFT class to self.noise_model.update_parameters(self.noise_model.gain, **kwargs). But it may cause errors with other noise models.

**Comment by tachella** [comment]
@samuro95 did you manage to look at this?
