### ISSUE TITLE
Merging parameters in the Downsampling class constructor

### ISSUE THREAD

**Issue by jscanvic** [deepinv/deepinv#28]
The Downsampling class constructor currently takes two parameters `filter` and `mode`, both of which are only used for initialising the field `filter`. If instead the two parameters were merged, the constructor might be clearer for the end-user.

https://github.com/deepinv/deepinv/blob/9de0018123ec7f78bf137caf0ebad090cdeb44b4/deepinv/physics/blur.py#LL103C19-L104C19

**Comment by tachella** [comment]
thanks for spotting this! it has been taking care of in a recent PR.
