### ISSUE TITLE
`datasets` ImportError

### ISSUE THREAD

**Issue by Andrewwango** [deepinv/deepinv#283]
If `datasets` is to be an optional requirement, then its import should be made optional in the datasets that use it. Otherwise it should be made a necessary requirement (although I would rather not, to keep requirements to a minimum).
https://github.com/deepinv/deepinv/blob/b22094cddb431294db3ed0ae90fa121c33436aed/deepinv/datasets/cbsd68.py#L4

**Comment by MaximeSongIdris** [comment]
datasets is necessary in cbsd68, but it is very specific to it
so the idea was to make `datasets` a optional module which can be installed along with other optional modules with
"pip install .[datasets]"

**Comment by MaximeSongIdris** [comment]
https://github.com/deepinv/deepinv/pull/286

I made an explicit error message if there is an import error, what do you think ?
