### ISSUE TITLE
define my own `physics.A`

### ISSUE THREAD

**Issue by tensor2023** [deepinv/deepinv#289]
Hello, I need to define a custom version of `physics.A` that fits my specific requirements, rather than using the one provided by the library. 
Is it possible to override the default `physics.A` with my own implementation? If so, could you please provide some guidance or examples on how to do this?

**Comment by matthieutrs** [comment]
Hi @tensor2023!

Yes, this is definitely possible. The way to do so is to create your own physics class inheriting from the physics class of interest. An example, provided [here](https://deepinv.github.io/deepinv/auto_examples/basics/demo_physics.html#sphx-glr-auto-examples-basics-demo-physics-py), is:

```python
# define an operator that converts color images into grayscale ones.
class MyClass(dinv.physics.LinearPhysics):
    r"""
    Here is my class converting RGB images to grayscale.

    Signals must be tensors with 3 colour (RGB) channels, i.e. [*,3,*,*]
    The measurements are grayscale images.
    """
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.noise_model = dinv.physics.GaussianNoise(sigma=0.1)

    def A(self, x, theta=None):  # theta is an optional parameter that is not used here
        y = x[:, 0, :, :] * 0.2989 + x[:, 1, :, :] * 0.5870 + x[:, 2, :, :] * 0.1140
        return y.unsqueeze(1)

    def A_adjoint(self, y, theta=None):
        return torch.cat([y * 0.2989, y * 0.5870, y * 0.1140], dim=1)


physics = MyClass()
```

After this, you still have access to the multiple operators associated to this physics, e.g. the pseudo-inverse, proximal operator, etc...

```python
x = torch.randn((1, 3, 16, 16)) # Define random 16x16 image
y = physics(x) # Compute measurements
x_dagger = physics.A_dagger(y) # Compute pseudoinverse
x_ = physics.prox_l2(y, torch.zeros_like(x), 0.1) # Compute prox at x=0
```

A more involved example is presented [here](https://deepinv.github.io/deepinv/auto_examples/advanced/demo_ri_basic.html#sphx-glr-auto-examples-advanced-demo-ri-basic-py).

Does that answer your question?

**Comment by tachella** [comment]
@tensor2023, please let us know if you have more questions, otherwise I will close this issue soon.

**Comment by tensor2023** [comment]
Thank you for your prompt response and assistance.
