### ISSUE TITLE
Cannot use no_learning method "prox_l2" with Downsampling operator through Trainer.test

### ISSUE THREAD

**Issue by VinceHerfeld** [deepinv/deepinv#303]
I am setting up experiments to do super-resolution, with the Downsampling physics operator.

When wanting to use `Trainer.test(...)` we can specify a `no_learning` method string. I have tried to change it to `"prox_l2"`.
`Trainer.test` calls : `physics.prox_l2(y)`
but the signature for Downsampling.prox_l2 is : `prox_l2(self, z, y, gamma, use_fft=True)`, so I have the following error:

`Downsampling.prox_l2() missing 2 required positional arguments: 'y' and 'gamma'`

**Comment by tachella** [comment]
thanks for spotting this bug - I'll fix asap.
