### ISSUE TITLE
Problem with adversarial.SupAdversarialDiscriminatorLoss device

### ISSUE THREAD

**Issue by devangelista2** [deepinv/deepinv#306]
This issue is to report a bug with the function: `adversarial.SupAdversarialDiscriminatorLoss(device=device)`, where I noticed that the `device` is not given as input to its super-class at declaration. This result in a bug where the tensor output of the loss function with `adversarial.SupAdversarialDiscriminatorLoss(device=device)` is always on cpu.

**Comment by Andrewwango** [comment]
Thanks @devangelista2 for raising the issue! Sorry, it was a small mistake in the code, I've fixed it in #296, hopefully it should be merged soon!
