### ISSUE TITLE
No Class Name "LRScheduler" in Pytroch

### ISSUE THREAD

**Issue by Acmonds** [deepinv/deepinv#314]
Hi there, please check if this needs to be corrected.

### Code error snippet:
deepinv/training/adversarial.py
```
from torch.optim.lr_scheduler import LRScheduler

class AdversarialScheduler:
    r"""Scheduler for adversarial training that encapsulates both generator and discriminator's schedulers.

    :param LRScheduler scheduler_g: generator's torch scheduler
    :param LRScheduler scheduler_d: discriminator's torch scheduler
    """

    def __init__(self, scheduler_g: LRScheduler, scheduler_d: LRScheduler):
        self.scheduler_g = scheduler_g
        self.scheduler_d = scheduler_d
```

### Return:

> Traceback (most recent call last):
>   File "/home/s*******/deepinv_playground/1.py", line 1, in <module>
>     import deepinv as dinv
>   File "/home/s*******/miniconda3/envs/py39/lib/python3.9/site-packages/deepinv/__init__.py", line 57, in <module>
>     from deepinv import training
>   File "/home/s*******/miniconda3/envs/py39/lib/python3.9/site-packages/deepinv/training/__init__.py", line 3, in <module>
>     from .adversarial import AdversarialTrainer, AdversarialOptimizer
>   File "/home/s*******/miniconda3/envs/py39/lib/python3.9/site-packages/deepinv/training/adversarial.py", line 6, in <module>
>     from torch.optim.lr_scheduler import LRScheduler
> ImportError: cannot import name 'LRScheduler' from 'torch.optim.lr_scheduler' 
> 

### Env：

> python                    3.9.19                
> torch                     1.7.1+cu110      

### Solve method：
Replace `LRScheduler` with `_LRScheduler`

**Comment by Andrewwango** [comment]
Thanks for raising the issue @Acmonds ! This is because LRScheduler was introduced in PyTorch 1.12 - I will make the imports optional as they are only needed for typing in #316 . Please can you check this fixes your problem?

**Comment by Acmonds** [comment]
Thank you, Andrew. That's helpful.
