### ISSUE TITLE
FEAT add `block=False` parameter to plot functions

### ISSUE THREAD

**Issue by mathurinm** [deepinv/deepinv#318]
`plot_*` functions in `deepinv.utils.plotting` use `plt.show()` which halts execution of the code until the matplotlib window is closed.

Would it make sense to use plt.show(block=False) instead in those?

**Comment by tachella** [comment]
yes indeed. For some reason, I don't have that issue when running deepinv via an ssh server, but it might be the case when used locally.

**Comment by Andrewwango** [comment]
I'm not sure about using `block=False` here. `block=False` has undesired behaviour such as plotting a frozen frame (e.g. see this [question](https://stackoverflow.com/questions/28269157/plotting-in-a-non-blocking-way-with-matplotlib)) and it gets a bit hacky to fix it. I would suggest, if you want non-blocking behaviour, to simply use `deepinv.utils.plot(show=False)` and then `plt.show(...)` in your own script. If you want more control you can

**Comment by mathurinm** [comment]
I'd be happy to have a block parameter in `plot` then, as MNE does for example : https://mne.tools/stable/generated/mne.Epochs.html#mne.Epochs.plot

but honestly maybe I'm the only one wishing for this feature

**Comment by jscanvic** [comment]
Hi @mathurinm Thanks for the suggestion! There's a workaround you might already know using the interactive mode from matplotlib with `plt.ion()` and `plt.ioff()` (see below). What do you think of it instead of having the extra argument?

```python
import torch
from matplotlib import pyplot as plt
from deepinv.utils import plot

for _ in range(5):
    # Set interactive mode locally
    with plt.ion():
        # Doesn't block.
        plot(torch.randn(1, 3, 128, 128))

# Blocks.
plot(torch.randn(1, 3, 128, 128))

# Set interactive mode globally
plt.ion()

for _ in range(5):
    # Doesn't block.
    plot(torch.randn(1, 3, 128, 128))

# Disable interactive mode globally
plt.ioff()

# Blocks.
plot(torch.randn(1, 3, 128, 128))
```

**Comment by mathurinm** [comment]
I'll try this, this seems like a lightweight workaround indeed. Thanks @jscanvic !
