### ISSUE TITLE
Poisson likelihood not matching poisson model

### ISSUE THREAD

**Issue by tachella** [deepinv/deepinv#322]
- the definition of [Poisson noise](https://deepinv.github.io/deepinv/stubs/deepinv.physics.PoissonNoise.html) has a gain parameter that does not match the [Poisson log-likelihood data fidelity](https://deepinv.github.io/deepinv/stubs/deepinv.optim.PoissonLikelihood.html).
- the normalization parameter of the Poisson log-likelihood is not matching the one in Poisson noise (I would remove it).
- docstrings are lacking in the definition of the Poisson log-likelihood.

@Nils-Laurent

**Comment by tachella** [comment]
this should be fixed in #282

**Comment by Andrewwango** [comment]
Has this been fixed?

**Comment by tachella** [comment]
Not at the doc level, I will fix this in my PR #347

**Comment by tachella** [comment]
this has been fixed in #347
