### ISSUE TITLE
Usage of PoissonNoise

### ISSUE THREAD

**Issue by Nils-Laurent** [deepinv/deepinv#350]
I tried to use `PoissonNoise` class with an image containing floats in [0, 1] in any of RGB channel. The problem is that I had a binary outputs (only zeros and ones in the channels of the noisy image).
In the code of `forward`, I noticed this line:

```
y = torch.poisson(
            torch.clip(x / self.gain, min=0.0) if self.clip_positive else x / self.gain,
            generator=self.rng,
        )
```

Does that mean the input has to be in [0, 255] ?

**Comment by tachella** [comment]
I think the code should work for values in $[0,1]$ as well, I don't see the issue...
Can I close it @Nils-Laurent ?

**Comment by Nils-Laurent** [comment]
Yes, you can close the Issue. I will look into it more in details

**Comment by Andrewwango** [comment]
Closing as not an issue
