### ISSUE TITLE
center the website

### ISSUE THREAD

**Issue by yuanzhi-zhu** [deepinv/deepinv#49]
Hi, thanks for your great work in developing such a great library.

I know this is somehow irrelevant, but I found the content in https://deepinv.github.io/deepinv/ is not centered in my browser (should be the same in other browsers too).

Is it possible to center the content? this will make the reading more joyful.

**Comment by tachella** [comment]
Hi Yuanzhi,

Many thanks for your interest in the library. Unfortunately, our docs use the [readthedocs template](https://readthedocs.org/) which is aligned to the left, and cannot be easily centered. We might consider in future versions to modify the template.
