### ISSUE TITLE
Appreciation, and Suggestion for New Physics Forward Operators about Interferometric Imaging

### ISSUE THREAD

**Issue by Guaishou74851** [deepinv/deepinv#66]
Hi,

I hope this message finds you well! I recently stumbled upon your amazing open-source project on GitHub for solving imaging inverse problems. I wanted to take a moment to express my admiration and gratitude for your remarkable work. I have been using **deepinv** for various simulation experiments and it has been incredibly helpful.

May I venture to ask if there are any plans to include new physics forward operators in the future? Specifically, I am interested in the possibility of incorporating physics operators related to **interferometric imaging** (e.g., https://github.com/HeSunPU/DPI, https://github.com/achael/eht-imaging) with applications to **astronomical radio interferometric imaging**. I believe this addition would greatly enhance **deepinv**'s capabilities and make it even more valuable to the user community.

Apologies for the interruption and any inconvenience caused. Thank you very, very much for your outstanding efforts, and I'm excited to see how this project evolves.

Best regards,
Bin Chen

**Comment by matthieutrs** [comment]
Hi @Guaishou74851, thanks for your interest in our library!

This was something we had in mind on the long run indeed. We are currently working on an implementation of non-uniform FFT (nufft) dependent operators for MRI, but our integration is slower than expected. A main difficulty is that we want to rely on a versatile torch, backward mode compatible (GPU and CPU) library, with minimal exotic dependencies. Unfortunately, I don't know yet when our implementation will be stable enough and pushed on main.

In the mean time, I'd happily assist you in implementing some RI operators on some branch/fork. We can start from there and see how easy (or not!) it is?

**Comment by matthieutrs** [comment]
Hey @Guaishou74851, just for the record we have now merged a version with a Radio Interferometric example implemented in torchkbnufft:

https://deepinv.github.io/deepinv/auto_examples/advanced/demo_ri_basic.html#sphx-glr-auto-examples-advanced-demo-ri-basic-py
