### ISSUE TITLE
Contributing guidelines and Discord link are not working

### ISSUE THREAD

**Issue by David-Morales-Norato** [deepinv/deepinv#75]
Hello, the links for the contributing guidelines and the discord server that you mentioned in the Readmeare not working.
![image](https://github.com/deepinv/deepinv/assets/46037413/028c29a0-136b-4e6e-9d02-0c07e7d381bc)

**Comment by tachella** [comment]
Hi David,

Thanks for spotting this bug, I've now replaced the link with [one that never expires](https://discord.gg/ZT9hMe3G). Thanks for joining the conversation!
