### ISSUE TITLE
Confusion between PnP-ULA and PPnP-ULA

### ISSUE THREAD

**Issue by Marien-RENAUD** [deepinv/deepinv#94]
About the PnP-ULA process. If you want to be precise, the current version of your code is PPnP-ULA (Projected-Plug-and-Play-Unajusted Langevin Algorithm) with the https://arxiv.org/abs/2103.04715 terminology.
The projection is strict on the set $[a,b]$. PnP-ULA will work with a penalization term for the projection $\frac{1}{\lambda} (\Pi_C(x) - x)$.
The two algorithms are closed but generate two different Markov Chain.

**Comment by matthieutrs** [comment]
Thanks a lot for raising this! I've clarified [here](https://github.com/deepinv/deepinv/blob/weights_reference/deepinv/sampling/langevin.py#L231), it should appear on the docs when merged.
